// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"changelog.md": () => import("../content/docs/changelog.md?collection=docs"), "community.md": () => import("../content/docs/community.md?collection=docs"), "download.md": () => import("../content/docs/download.md?collection=docs"), "contribute/contributors.md": () => import("../content/docs/contribute/contributors.md?collection=docs"), "contribute/overview.md": () => import("../content/docs/contribute/overview.md?collection=docs"), "contribute/support-me.md": () => import("../content/docs/contribute/support-me.md?collection=docs"), "contribute/website-development.md": () => import("../content/docs/contribute/website-development.md?collection=docs"), "faq/compatibility.md": () => import("../content/docs/faq/compatibility.md?collection=docs"), "faq/general.md": () => import("../content/docs/faq/general.md?collection=docs"), "faq/optimizing.md": () => import("../content/docs/faq/optimizing.md?collection=docs"), "faq/troubleshooting.md": () => import("../content/docs/faq/troubleshooting.md?collection=docs"), "features/bloatware.md": () => import("../content/docs/features/bloatware.md?collection=docs"), "features/customize.md": () => import("../content/docs/features/customize.md?collection=docs"), "features/disk-cleanup.md": () => import("../content/docs/features/disk-cleanup.md?collection=docs"), "features/optimize.md": () => import("../content/docs/features/optimize.md?collection=docs"), "features/scheduled-tasks.md": () => import("../content/docs/features/scheduled-tasks.md?collection=docs"), "features/startup-manager.md": () => import("../content/docs/features/startup-manager.md?collection=docs"), "guides/best-practices.md": () => import("../content/docs/guides/best-practices.md?collection=docs"), "guides/getting-started.md": () => import("../content/docs/guides/getting-started.md?collection=docs"), "guides/how-it-works.md": () => import("../content/docs/guides/how-it-works.md?collection=docs"), "guides/uninstall.md": () => import("../content/docs/guides/uninstall.md?collection=docs"), "faq/troubleshooting/antivirus.md": () => import("../content/docs/faq/troubleshooting/antivirus.md?collection=docs"), "faq/troubleshooting/app-wont-open.md": () => import("../content/docs/faq/troubleshooting/app-wont-open.md?collection=docs"), "faq/troubleshooting/download.md": () => import("../content/docs/faq/troubleshooting/download.md?collection=docs"), "faq/troubleshooting/revert-changes.md": () => import("../content/docs/faq/troubleshooting/revert-changes.md?collection=docs"), "faq/troubleshooting/slow-performance.md": () => import("../content/docs/faq/troubleshooting/slow-performance.md?collection=docs"), "faq/troubleshooting/smartscreen.md": () => import("../content/docs/faq/troubleshooting/smartscreen.md?collection=docs"), }),
};
export default browserCollections;